gitSourceBranch = "main"

[docusaurus]
url = "https://matter-ecs.github.io/"
baseUrl = "/matter"
tagline = "A modern ECS library for Roblox"

[[classOrder]]
classes = ["Matter", "World", "QueryResult", "Loop"]

[[classOrder]]
section = "Components"
classes = ["Component", "TableComponentInstance"]

[[navbar.items]]
href = "https://discord.gg/aQwDAYhqtJ"
label = "Roblox Open Source Discord"
position = "right"

[[navbar.items]]
href = "https://patreon.com/erynlynn"
label = "Support on Patreon"
position = "right"

[navbar]
title = ""

[navbar.logo]
alt = "Matter"
src = "/logo.svg"

[home]
enabled = true
includeReadme = false
